### ISSUE TITLE
Repo Sync Failing

### ISSUE THREAD

**Issue by sizemorebrian** [boundarydevices/boundary-bsp-platform#1]
When I run repo sync I get the following errors:

```
Fetching projects:  70% (7/10)  fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection refused

Fetching projects:  90% (9/10)  fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection refused
```

I would guess there are missing repositories?
I verified that I could connect to github.com during these times:

```
ping 192.30.253.113 -c 1
PING 192.30.253.113 (192.30.253.113) 56(84) bytes of data.
64 bytes from 192.30.253.113: icmp_seq=1 ttl=55 time=10.7 ms

ping github.com -c 1
PING github.com (192.30.253.113) 56(84) bytes of data.
64 bytes from 192.30.253.113: icmp_seq=1 ttl=55 time=9.94 ms
```

Then once again tried to repo sync and get the same errors.

**Comment by gibsson** [comment]
Hi,
Sorry for the delay, this issue wasn't notified to us. Do you still have that issue? Which branch are you using?
Regards

**Comment by gibsson** [comment]
As there's been so reply on this it is assumed outdated. So closing it.
