### ISSUE TITLE
Build error on branch warrior

### ISSUE THREAD

**Issue by ivando0209** [boundarydevices/boundary-bsp-platform#4]
I have synced this repo, branch warrior and got error when compiling. Please give me some advices

`MACHINE=nitrogen6x DISTRO=fslc-x11 . setup-environment build_nitrogen6x_x11/
bitbake boundary-image-multimedia-full`

Error is:

`ERROR: linux-boundary-4.14.x-r0 do_patch: Command Error: 'quilt --quiltrc /home/ivando/Disk0/Linux/src/build_nitrogen6x_x11/tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/4.14.x-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-Add-support-for-koe-tx31d200vm0baa-display.patch
patching file arch/arm/boot/dts/imx6qdl-nitrogen6x.dtsi
Hunk #1 FAILED at 493.
Hunk #2 succeeded at 1086 (offset 28 lines).
1 out of 2 hunks FAILED -- rejects in file arch/arm/boot/dts/imx6qdl-nitrogen6x.dtsi
Patch 0001-Add-support-for-koe-tx31d200vm0baa-display.patch does not apply (enforce with -f)
ERROR: linux-boundary-4.14.x-r0 do_patch:
ERROR: linux-boundary-4.14.x-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/ivando/Disk0/Linux/src/build_nitrogen6x_x11/tmp/work/nitrogen6x-fslc-linux-gnueabi/linux-boundary/4.14.x-r0/temp/log.do_patch.13604
ERROR: Task (/home/ivando/Disk0/Linux/src/sources/meta-boundary/recipes-kernel/linux/linux-boundary_4.14.x.bb:do_patch) failed with exit code '1'
ERROR: qtbase-5.14.0+gitAUTOINC+51edfdd212-r0 do_patch: Command Error: 'quilt --quiltrc /home/ivando/Disk0/Linux/src/build_nitrogen6x_x11/tmp/work/cortexa9t2hf-neon-mx6qdl-fslc-linux-gnueabi/qtbase/5.14.0+gitAUTOINC+51edfdd212-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0002-Disable-ltcg-for-windows-and-static-libs.patch
patching file mkspecs/features/ltcg.prf
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file mkspecs/features/ltcg.prf
Patch 0002-Disable-ltcg-for-windows-and-static-libs.patch does not apply (enforce with -f)
ERROR: qtbase-5.14.0+gitAUTOINC+51edfdd212-r0 do_patch:
ERROR: qtbase-5.14.0+gitAUTOINC+51edfdd212-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/ivando/Disk0/Linux/src/build_nitrogen6x_x11/tmp/work/cortexa9t2hf-neon-mx6qdl-fslc-linux-gnueabi/qtbase/5.14.0+gitAUTOINC+51edfdd212-r0/temp/log.do_patch.13588
ERROR: Task (/home/ivando/Disk0/Linux/src/sources/meta-qt5/recipes-qt/qt5/qtbase_git.bb:do_patch) failed with exit code '1'`

**Comment by bmx666** [comment]
@ivando0209 there are several patches which doesn't applied correctly. You can fix and override them manually in repo and create pull-request or exclude them by **SRC_URI_remove**  if they was already applied.
