### ISSUE TITLE
meta-clang master is broken

### ISSUE THREAD

**Issue by bmx666** [boundarydevices/boundary-bsp-platform#7]
Few days ago meta-clang pushed commit and it breaks all manifests
I made the issue https://github.com/kraj/meta-clang/issues/651 but seems issue is related to BoundaryDevice manifests and they should point on correct branches instead of "master"

**Comment by chrisdimich** [comment]
@bmx666 this may be true, but actually we no longer use meta-clang layer anyways in bblayers, so was going to remove it for now (we may add it back at a later date). Are you using it in your bblayers.conf file? I think when we used it, we had to use master as the current yocto release branch at that time did not exist in this layer.

**Comment by bmx666** [comment]
Hi @chrisdimich, I included into my manifest these lines:
```xml
  <remove-project name="meta-clang"/>
  <project remote="clang" name="meta-clang" path="sources/meta-clang"/>
```

Anyway, I used it only for `meta-browser` layer for **Chromium**, but after few tests I decided to switch on `meta-qt5` and **qt-kiosk-browser**
